---
- name: install/update vim
  homebrew: name=vim state=latest install_options=with-lua

- name: install/update ctags
  homebrew: name=ctags state=latest

- name: ensure spf13 is installed
  shell: curl https://j.mp/spf13-vim3 -L -o - | sh
  args:
    creates: ~/.spf13-vim-3/.vimrc
  notify: vim plugin install

- name: update spf13
  git:
  args:
    repo: https://github.com/spf13/spf13-vim.git
    dest: ~/.spf13-vim-3
  notify: vim plugin install

- name: add .fork shims for stack.d support
  copy: src={{ item }} dest=~/.{{ item }}
  with_items:
    - vimrc.bundles.fork
    - vimrc.before.fork
    - vimrc.fork

- name: add configuration to stack.d
  copy: src={{ item }} dest={{ stack_d }}
  with_items:
    - vim.bundle
    - vim.vimrc.before
    - vim.vimrc
    - vim.zsh
  notify: vim plugin install
